version: "3.8"

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - db-store:/var/lib/mysql
    env_file:
      - ./.env
    expose:
      - 13306
    ports:
      - 13306:3306
    healthcheck:
      # dbコンテナにpingを実行(環境変数は「dockerfiles/mysql/.env」で定義)
      test: mysqladmin ping -h 0.0.0.0 -u$$MYSQL_USER -p$$MYSQL_PASSWORD 
  app:
    container_name: python
    build:
      context: .
      dockerfile: ./dockerfiles/python/Dockerfile
    volumes:
      - ./src:/src
      - ./static:/static
    env_file:
      - ./.env
    tty: true
    expose:
      - 15000
    ports:
      - 15000:15000
    # command:  bash -c "python $DJANGO_ROOT/manage.py collectstatic --noinput"
#              python $DJANGO_ROOT/manage.py migrate && \
#              gunicorn --chdir $DJANGO_ROOT $DJANGO_PROJECT.wsgi:application --bind 0.0.0.0:15000"
    # command: gunicorn --chdir $DJANGO_ROOT $DJANGO_PROJECT.wsgi:application --bind 0.0.0.0:15000
    depends_on:
      - db
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    volumes:
      - ./dockerfiles/nginx/django.conf:/etc/nginx/conf.d/django.conf
      - ./src/$DJANGO_ROOT/static:/static  # この設定を追加
    expose:
      - 8080
    ports:
      - 8080:8080
    tty: true
    working_dir: /workspace
    depends_on:
      - app

volumes:
  db-store: