### 本番環境用コンテナ設定ファイル ###
version: "3.8"

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - db-store:/var/lib/mysql
    env_file:
      - ./.env
    expose:
      - 13306
    ports:
      - 13306:3306
    healthcheck:
      # dbコンテナにpingを実行(環境変数は「dockerfiles/mysql/.env」で定義)
      test: mysqladmin ping -h 0.0.0.0 -u$$MYSQL_USER -p$$MYSQL_PASSWORD 
  app:
    container_name: python
    build:
      context: .
      dockerfile: ./dockerfiles/python/Dockerfile
    volumes:
      - ./src:/src
      - ./src/static:/static  # この設定を追加
    env_file:
      - ./.env
    tty: true
    expose:
      - 15000
    ports:
      - 15000:15000
    entrypoint: bash -c "sh /tmp/entrypoint.sh"
    depends_on:
      db:
        condition: service_healthy
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    volumes:
      - ./dockerfiles/nginx/django.conf:/etc/nginx/conf.d/django.conf
      - ./src/static:/static  # この設定を追加
    expose:
      - 8080
    ports:
      - 8080:8080
    tty: true
    working_dir: /static
    depends_on:
      - app

volumes:
  db-store:
  static: