version: "3.8"

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - db-store:/var/lib/mysql
    env_file:
      - ./.env
    healthcheck:
      # dbコンテナにpingを実行(環境変数は「dockerfiles/mysql/.env」で定義)
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD 
  app:
    container_name: python
    build:
      context: .
      dockerfile: ./dockerfiles/python/Dockerfile
    volumes:
      - ./src:/src
      - ./static:/static
    # command:  bash -c "python manage.py collectstatic --noinput && \
    #           gunicorn $$DJANGO_PROJECT.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env
    tty: true
    expose:
      - "5000"
    depends_on:
      - db
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    volumes:
      - ./dockerfiles/nginx/django.conf:/etc/nginx/conf.d/django.conf
    ports:
      - 8080:8080
    tty: true
    working_dir: /workspace
    depends_on:
      - app

volumes:
  db-store: